<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Services\GoogleCalendarService;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Log;

/**
 * Google Calendar OAuth for merchants.
 *
 * This app authenticates dashboard requests with a Bearer token stored in
 * localStorage (no server session), so the OAuth round-trip cannot rely on
 * Auth::user() in the browser-navigated callback. Instead the merchant identity
 * is carried through Google's `state` parameter as an encrypted, time-limited
 * payload generated by an authenticated API call (`connectUrl`).
 */
class GoogleOAuthController extends Controller
{
    /**
     * How long a generated OAuth state stays valid (seconds).
     */
    private const STATE_TTL = 600;

    public function __construct(
        protected GoogleCalendarService $calendarService
    ) {}

    /**
     * API (auth:sanctum): return the Google consent URL with a signed state
     * that identifies the merchant. The frontend navigates the browser to it.
     */
    public function connectUrl(Request $request): JsonResponse
    {
        $user = $request->user();

        if (! $user) {
            return response()->json(['success' => false, 'message' => 'Unauthorized'], 401);
        }

        // Calendar is owned by the master account (effective user id).
        $ownerId = $user->getEffectiveUserId();
        $state = Crypt::encryptString($ownerId.'|'.time());

        try {
            return response()->json([
                'success' => true,
                'url' => $this->calendarService->getAuthorizationUrl($state),
            ]);
        } catch (Exception $e) {
            Log::error('Failed to generate Google OAuth URL', [
                'error' => $e->getMessage(),
                'user_id' => $ownerId,
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Gagal menghubungkan ke Google Calendar. Silakan coba lagi.',
            ], 500);
        }
    }

    /**
     * Web: Google redirects here after consent. The merchant is resolved from
     * the encrypted `state`, not from a session.
     */
    public function handleGoogleCallback(Request $request): RedirectResponse
    {
        $redirectTo = redirect('/dashboard/reservations/config');

        if ($request->has('error')) {
            Log::warning('Google OAuth authorization denied', [
                'error' => $request->get('error'),
            ]);

            return $redirectTo->with('error', 'Otorisasi Google Calendar dibatalkan.');
        }

        if (! $request->filled('code') || ! $request->filled('state')) {
            return $redirectTo->with('error', 'Kode otorisasi tidak ditemukan.');
        }

        $user = $this->resolveUserFromState($request->get('state'));

        if (! $user) {
            return $redirectTo->with('error', 'Sesi otorisasi tidak valid atau kedaluwarsa. Silakan coba lagi.');
        }

        try {
            $token = $this->calendarService->authenticate($request->get('code'));

            $user->update([
                'google_calendar_refresh_token' => json_encode($token),
                'google_calendar_email' => $this->getEmailFromToken($token, $user),
            ]);

            Log::info('Google Calendar connected successfully', [
                'user_id' => $user->id,
                'email' => $user->google_calendar_email,
            ]);

            return $redirectTo->with('success', 'Google Calendar berhasil terhubung! Reservasi baru akan otomatis masuk ke kalender Anda.');
        } catch (Exception $e) {
            Log::error('Failed to handle Google OAuth callback', [
                'error' => $e->getMessage(),
                'user_id' => $user->id,
            ]);

            return $redirectTo->with('error', 'Gagal menghubungkan Google Calendar: '.$e->getMessage());
        }
    }

    /**
     * API (auth:sanctum): disconnect Google Calendar for the merchant.
     */
    public function disconnectCalendar(Request $request): JsonResponse
    {
        $user = $request->user();

        if (! $user) {
            return response()->json(['success' => false, 'message' => 'Unauthorized'], 401);
        }

        $ownerId = $user->getEffectiveUserId();
        $owner = $ownerId === $user->id ? $user : User::find($ownerId);

        if (! $owner) {
            return response()->json(['success' => false, 'message' => 'Akun tidak ditemukan'], 404);
        }

        $owner->update([
            'google_calendar_refresh_token' => null,
            'google_calendar_email' => null,
        ]);

        Log::info('Google Calendar disconnected', ['user_id' => $owner->id]);

        return response()->json([
            'success' => true,
            'message' => 'Google Calendar berhasil diputuskan.',
        ]);
    }

    /**
     * Decrypt and validate the OAuth state, returning the owning merchant.
     */
    protected function resolveUserFromState(string $state): ?User
    {
        try {
            [$userId, $issuedAt] = array_pad(explode('|', Crypt::decryptString($state), 2), 2, null);

            if (! $userId || ! $issuedAt || (time() - (int) $issuedAt) > self::STATE_TTL) {
                return null;
            }

            return User::find((int) $userId);
        } catch (Exception $e) {
            Log::warning('Invalid Google OAuth state', ['error' => $e->getMessage()]);

            return null;
        }
    }

    /**
     * Extract the connected calendar email, falling back to the user's email.
     */
    protected function getEmailFromToken(array $token, User $user): ?string
    {
        try {
            $this->calendarService->setAccessToken(json_encode($token));

            return $this->calendarService->getCalendarEmail() ?? $user->email;
        } catch (Exception $e) {
            Log::warning('Failed to get email from calendar', ['error' => $e->getMessage()]);

            return $user->email;
        }
    }
}
