<?php

namespace App\Http\Controllers;

use App\Models\Reservation;
use App\Services\GoogleCalendarService;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\View\View;

/**
 * Handles the buyer-side Google Calendar OAuth flow.
 *
 * Flow:
 *   1. ReservationFulfillmentService checks buyer email in buyer_calendar_tokens.
 *   2. If NOT found → sends WA with link to /calendar/buyer/connect?token={signed}
 *   3. Buyer taps link → this controller redirects to Google consent screen.
 *   4. Google redirects to /calendar/buyer/callback with code + state.
 *   5. Token is stored; pending reservation event is created immediately.
 *   6. Buyer sees a success page confirming the connection.
 *
 * All future reservations for this email are handled automatically.
 */
class BuyerCalendarOAuthController extends Controller
{
    public function __construct(
        protected GoogleCalendarService $calendar,
    ) {}

    /**
     * Short-link resolver: /c/{code} → /calendar/buyer/connect?token={fullToken}
     *
     * The short code was stored in cache by ReservationFulfillmentService when
     * the WhatsApp message was sent. Resolves and redirects to the connect flow.
     */
    public function connectShort(Request $request, string $code)
    {
        $fullToken = Cache::get("cal_connect:{$code}");

        if (! $fullToken) {
            return view('calendar.buyer-connect-result', [
                'success' => false,
                'message' => 'Tautan sudah kadaluarsa (berlaku 24 jam). Silakan lakukan reservasi baru atau hubungi merchant untuk mendapatkan link baru.',
            ]);
        }

        // Consume the short code immediately (one-time use).
        Cache::forget("cal_connect:{$code}");

        // Redirect to the full connect flow with the resolved token.
        return redirect()->route('buyer.calendar.connect', ['token' => $fullToken]);
    }

    /**
     * Redirect the buyer to Google's OAuth consent screen.
     *
     * The `token` query param is a signed payload containing the buyer's
     * email + reservation_id, generated by ReservationFulfillmentService.
     */
    public function connect(Request $request): RedirectResponse
    {
        $token = $request->query('token');

        if (! $token) {
            abort(400, 'Tautan tidak valid.');
        }

        try {
            // Decrypt the token to extract email + reservation_id.
            $parts = explode('|', \Illuminate\Support\Facades\Crypt::decryptString($token), 3);
            [$email, $reservationId] = array_pad($parts, 2, null);

            if (! $email || ! $reservationId) {
                abort(400, 'Tautan tidak valid atau telah kadaluarsa.');
            }

            $authUrl = $this->calendar->getBuyerAuthUrl($email, (int) $reservationId);

            return redirect()->away($authUrl);

        } catch (Exception $e) {
            Log::warning('BuyerCalendarOAuth: invalid connect token', [
                'error' => $e->getMessage(),
            ]);

            abort(400, 'Tautan tidak valid atau telah kadaluarsa. Silakan minta link baru.');
        }
    }

    /**
     * Google redirects here after the buyer grants permission.
     * Store the token, create the pending reservation event, show success page.
     */
    public function callback(Request $request): View|RedirectResponse
    {
        if ($request->has('error')) {
            Log::info('BuyerCalendarOAuth: buyer denied permission', [
                'error' => $request->input('error'),
            ]);

            return view('calendar.buyer-connect-result', [
                'success' => false,
                'message' => 'Anda membatalkan koneksi Google Calendar. Anda masih bisa menambahkan reservasi ke kalender secara manual menggunakan link yang telah dikirimkan.',
            ]);
        }

        if (! $request->filled('code') || ! $request->filled('state')) {
            return view('calendar.buyer-connect-result', [
                'success' => false,
                'message' => 'Respons dari Google tidak lengkap. Silakan coba lagi.',
            ]);
        }

        try {
            $state = $request->input('state');

            // Exchange code for token and persist it.
            $stored = $this->calendar->authenticateBuyer(
                $request->input('code'),
                $state
            );

            // Immediately create the calendar event for the pending reservation
            // that triggered this connect flow.
            $reservationId = $this->calendar->reservationIdFromBuyerState($state);
            $reservationName = null;
            if ($reservationId) {
                $reservation = Reservation::with(['store', 'table'])
                    ->find($reservationId);

                if ($reservation) {
                    $this->calendar->createEventForBuyer($reservation);
                    $reservationName = $reservation->store?->name;
                }
            }

            Log::info('BuyerCalendarOAuth: calendar connected successfully', [
                'email'          => $stored->email,
                'reservation_id' => $reservationId,
            ]);

            return view('calendar.buyer-connect-result', [
                'success'         => true,
                'email'           => $stored->email,
                'reservation_name'=> $reservationName,
                'message'         => 'Google Calendar Anda berhasil terhubung! Reservasi ini telah ditambahkan ke kalender Anda, dan reservasi mendatang akan ditambahkan secara otomatis.',
            ]);

        } catch (Exception $e) {
            Log::error('BuyerCalendarOAuth: callback failed', [
                'error' => $e->getMessage(),
            ]);

            return view('calendar.buyer-connect-result', [
                'success' => false,
                'message' => 'Gagal menghubungkan Google Calendar. Silakan coba lagi dari link yang dikirimkan di WhatsApp Anda.',
            ]);
        }
    }
}
